### ISSUE TITLE
Problem - App is not spiderable. Phantom is killed.

### ISSUE THREAD

**Issue by LeCoupa** [gadicc/meteor-phantomjs#5]
Hello and thank you for this package!

I have already seen #1 but I get the same error message (both on local and production). PhantomJS is correctly set up on these two environments (running phantomjs -v displays the current version).

```
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
```

Is there a way to display what is going wrong with PhantomJS? I just read [in this thread](https://groups.google.com/forum/#!topic/meteor-talk/7ZbidddRGo4) that someone succeed to display "SyntaxError: Parse error". I think that my problem is also due to the minification but I am not using observatory or select2. (All my publications also return a selector)

**Comment by gadicc** [comment]
Wow, sorry!  I'm finding all GitHub issues today that slipped past me :(  Did you ever get this working?

There is an extensive script at the bottom of http://meteorpedia.com/read/spiderable which instructions on how to figure out these kind of problems.  Usually.  Note also that urlify has been also been reported to cause these issues too (same problem, it gets minified and phantomjs doesn't recognize all the symbols).

**Comment by LeCoupa** [comment]
It was the SSL issue. :)
