### ISSUE TITLE
PhantomJS timing out on Modulus

### ISSUE THREAD

**Issue by Lepozepo** [gadicc/meteor-phantomjs#6]
Hi,

I tested heavily to try to find out what was causing issues with PhantomJS in production (Modulus) and have found that adding a custom domain is part of the problem. I have already contacted their support team and I'm waiting for them to help me out but do you have any idea why something like this could happen?

Maybe the code needs to support custom domains somehow?

Thanks for your time ^_^

**Comment by gadicc** [comment]
You need to make sure that your custom domain is accessible from the server itself.  Consider:

`client` (internet) --> load balancer `LB` --> `server`

All custom domains map to `LB`, which then routes on an internal network to `server`.  `LB` of course accepts connections from anywhere on the external internet interface, but perhaps does not accept connections (either by firewall or routing policy) on it's external IP originating on the internal network.

Note since Meteor v0.8.1.3, spiderable ignores the host header and instead always connects to the ROOT_URL.  Which is usually, but not always, a help in situations like this.  i.e. you need to make sure that connections originating from the _server_ can connect to port 80 of the host specified in ROOT_URL.

Hope that helps!  I think the Modulus guys are familiar with Meteor but you might want to pass this info on to them in case.

**Comment by gadicc** [comment]
I'm closing this since it isn't a bug.  But I'm happy to keep chatting here until we get this resolved.

**Comment by Lepozepo** [comment]
I started using spiderfork instead of spiderable. That fixed all issues on sites that do not have an SSL certificate (for modulus at least). Still, my site does have an SSL certificate and it's still timing out. I forked and modified spiderfork like this:

```
line 89
("exec phantomjs --debug=true --ssl-protocol=TLSv1 --ignore-ssl-errors=true --load-images=no /dev/stdin <<'END'\n" +
```

It still doesn't work but for some reason googlebot is actually detecting the sites "loading" template (it never successfully connects).

Are there any other options I could try to add that might fix this?

**Comment by manybothans** [comment]
@Lepozepo Hey, I'm having the same issue, did you come up with a solution?

**Comment by Lepozepo** [comment]
@manybothans I haven't found a solution to the SSL issue yet :/ maybe if the site is served on a dedicated server it would work with SSL but I'm not certain.

**Comment by manybothans** [comment]
@Lepozepo spiderfork seemed to work for me!

**Comment by Lepozepo** [comment]
Damn! Over SSL? What's the domain?

**Comment by manybothans** [comment]
@Lepozepo https://canlio.com yeah, the ignore-ssl-errors seemed to be all I needed! i'm upgrading to an EV wildcard cert in a week or so, we'll see if that still works.

**Comment by Lepozepo** [comment]
@manybothans Where are you hosting your site? Do you use demeteorizer?

**Comment by manybothans** [comment]
@Lepozepo hosting on AWS via modulus.io. I didn't run demeteorizer myself, but I think modulus runs it as part of the `modulus deploy` process.

**Comment by Lepozepo** [comment]
Have you tried testing with this code snippet for phantomjs? http://www.meteorpedia.com/read/spiderable/

My site fails that one but seems to spit the loading page for googlebot, lol.

**Comment by manybothans** [comment]
@Lepozepo Hm, thanks for the tip. I've just been testing using curl and the the facebook open graph debugger, but this test fails. Guess I don't have the magic touch afterall! ;)

I'll report back if I find anything out, if you'll do the same!

**Comment by Lepozepo** [comment]
I will ^_^

**Comment by manybothans** [comment]
Do you think it's an issue with just using a single domain certificate? (I think I read that somewhere in a different thread). I'm getting an enhanced verification certificate for wildcard subdomain in about a week (I hope)... I hope that clears it up.

**Comment by manybothans** [comment]
The other weird thing is that we've already started showing up in google search results.... very strange indeed.

**Comment by stevenhornung** [comment]
Any luck here? I'm still having issues with spiderable. I tried using spiderable-ssl which has --ignore-ssl-errors=true and --ssl-protocol=TLSv1 but no luck.  I'm hosted on modulus with a custom wildcard domain cert.

**Comment by manybothans** [comment]
@stevenhornung Still no luck. I'm having the same issue as @Lepozepo; Google sees the page but is just getting the loading template, not the content. The meta tags from ms-seo package seem to be working, so crawling is like half there :-/. If you find a fix please Please PLEASE report it back here!

**Comment by stevenhornung** [comment]
I ended up hosting phantomjs on a remote machine and I am using a modified spiderable-remote and phantomjs-remote package and crawling is working great now.

**Comment by manybothans** [comment]
@stevenhornung are you using a fully separate remote server, or just a separate modulus app?

**Comment by stevenhornung** [comment]
Hosted on a separate EC2 instance
