### ISSUE TITLE
Confused on how to access the phantom smart package in code

### ISSUE THREAD

**Issue by sferoze** [gadicc/meteor-phantomjs#7]
Hi

I install phantomjs smart package using 'mrt add phantomjs' and it installed successfully. 

Now I want to use phantomjs and I was wondering if I need to add: 

phantom = Meteor.require('phantom') 
or just the regular require statement?

or something to get the phantom object. I tried the above with no success. 

I want to use phantomjs to take a screenshot like specified here: http://phantomjs.org/screen-capture.html

var page = require('webpage').create();
page.open('http://github.com/', function() {
  page.render('github.png');
  phantom.exit();
});

but once I have installed the meteor-phantomjs smart package I am not sure what I need to do in order to access it. Any help would be really appreciated, thanks!

**Comment by gadicc** [comment]
Hey.  Actually, this is a bit confusing, I guess because everyone is using phantomjs just for spiderable.  All this smart package does it get it installed for you and add it to the path in Meteor, it doesn't actually provide any interface to phantomjs.  And amazingly even though the package is a year old, you're the first person to run into this confusion :>

Check out doingthiswith.meteor.com for an example of using phantomjs for screenshots, there's a link to the full source.  I think we used a module called 'webshot'.  Both packages will probably work well together, phantomjs to install phantomjs and webshot to interface with it.

**Comment by sferoze** [comment]
Ah thanks very much.

I checked out doingthiswith.meteor and the thumbs of the apps are very similar to what I am trying to do. 

I checked out the source file webshot.js and saw that:

 var webshot = Async.wrap(Meteor.require('webshot'));
 var gm = Meteor.require('gm');
 var im = gm.subClass({ imageMagick: true });
 var fs = Meteor.require('fs');

Looks like webshot is required which I can install. But I do not notice phantomjs being used. I am not sure what gm is. 

Is all the source code used to take the image of an external url in webshot.js?

**Comment by sferoze** [comment]
From the looks of the documentation I can just use the webshot module. No need for the phantomjs unless phantomjs is required for webshot, but it doesnt look like it

**Comment by gadicc** [comment]
Yeah, you don't use phantomjs directly... webshot is a thin wrapper around it.  The phantomjs smart package will just make sure it's installed for you.  (Or I guess if the webshot npm module includes the phantomjs npm module, that's essentially the same thing).

gm = graphicsmagick.  and imagemagick.  two (mostly interchangeable) libraries for processing images.  you'll need it if you need to resize the screenshots (e.g. to make thumbnails).  And unfortunately they're not available on all PaaS hosts (or meteor.com).  If you don't need to resize the screenshots (potentially you could just render to a screen/window dimension and change the zoom... but beyond a certain smallish point this looks terrible) - then you can get by without it.

I'm pretty sure all the code is in that one file but I don't recall off hand.  I also used CollectionFS' S3 module to store the image on Amazon, which of course you can avoid if you only have a single server with persistence.

**Comment by sferoze** [comment]
Man I am having issues trying to get webshot to simply work with Meteor. I added the meteor smart package and am using the example code to try and just save a screenshot to the server but nothing is saved! I started a stackoverflow question, if you have any advice it would be much appreciated!

http://stackoverflow.com/questions/24441963/meteor-webshot-is-not-working-to-take-a-screenshot-and-save-it-on-the-server

**Comment by numtel** [comment]
I had this same issue today and finally came up with a good explanation:
- This package ensures phantomjs is installed and then provides the path to the executable.

From this understanding, you must call phantomjs with your script.

**server/server.js:**

```
var phantomjs = Npm.require('phantomjs');
var spawn = Npm.require('child_process').spawn;
Meteor.methods({
  runTest: function(options){
    command = spawn(phantomjs.path, ['assets/app/phantomDriver.js']);
    command.stdout.on('data',  function (data) {
      console.log('stdout: ' + data);
    });
    command.stderr.on('data', function (data) {
      console.log('stderr: ' + data);
    });
    command.on('exit', function (code) {
      console.log('child process exited with code ' + code);
    });
  }
});
```

**private/phantomDriver.js:**

```
var page = require('webpage').create();
page.open('http://github.com/', function() {
    console.log('Page Loaded');
    page.render('github.png');
    phantom.exit();
});
```

Having never used PhantomJS before, it took me a bit to grasp that it ran a script in its own context as a command line app. I thought all the code would go into server/server.js. This example (or one like it) would be useful in the readme.

**Comment by gadicc** [comment]
Hey, you're the second person to bring this up, so I guess it's time I did something about it :)  I clarified the purpose of the package in the README and gave your example code.  Many thanks :)

**Comment by adamgins** [comment]
@gadicc how goes? Just wondering if you have an example you could share, saving a PhantomJS/Webshot screen grab using CFS-s3, please?... about to try it out.. but thought I may as well ask. 

BTW, I had PhantomJS working... grabbing text content. I could not get it working with images... so using node-webshot... which seems to return with no error but it does not save the image anywhere (I can find). I have "gadicohen:phantomjs                      0.0.2 " installed. 

The example, I am trying to run is:

```
 var webshot = Meteor.npmRequire('webshot');

    webshot('google.com', '/~exports/google.png', function(err) {
        console.log("in webshot, err:" + err);
        // screenshot now saved to google.png
    });
```

Any help appreciated.

**Comment by numtel** [comment]
Hello Adam,
I got a notification as I posted on this issue a while back.

If that's the entirety of your webshot code, you probably need to specify the `phantomPath` option.

``` javascript
 var webshot = Meteor.npmRequire('webshot');

    webshot('google.com', '/~exports/google.png', {
         phantomPath: phantomjs.path
    }, function(err) {
        console.log("in webshot, err:" + err);
        // screenshot now saved to google.png
    });
```

Hope that helps,
Ben

**Comment by adamgins** [comment]
@numtel thanks for the quick response. I just ran 

```
 webshot('google.com',
        '/~exports/google.png',
        {
            phantomPath: "/opt/phantomjs/bin/phantomjs"
        },
        function(err) {
            console.log("in webshot, err:" + err);
            // screenshot now saved to google.png
    });

```

Any same thing... I get nothing back ... also I see in the console is "in webshot, err:null"...  I searched my hard drive fro "google.png", nothing.

Must be something silly I am doing.

**Comment by adamgins** [comment]
@numtel maybe I'll try your package https://atmospherejs.com/numtel/phantomjs-persistent-server instead? I was just fishing around my /opt directory and see there was one github.png image saved there from one of my earlier attempts today... not sure how I got it to work (kinda). That said the image is only 542 bytes, so something must have not worked... but better than where I am with the straight npm approach.

**Comment by gadicc** [comment]
hey all, a bit short on time these days but there's an example here:

https://github.com/gadicc/meteor-doingthiswith/blob/6e1e347687459382349b8c733004271e8cfcde18/pages/apps/webshots.js

demo: https://doingthiswith.wastelands.net/apps

(the forever spinning ones are where people didn't give a URL, didn't think to accommodate that :)).

**Comment by xamlit** [comment]
@adamgins Did you ever find a solution to this problem? I'm having the same exact symptoms as you are. No errors are being reported and evidently no files created. Please advise?

**Comment by adamgins** [comment]
@xamlit no sorry... I deprioritised this feature and just used user selected  images for snapshots
