### ISSUE TITLE
Phantomjs working on one Modulus install but not another

### ISSUE THREAD

**Issue by manybothans** [gadicc/meteor-phantomjs#8]
Hey again,

So I have 2 fresh modulus apps on my account. One is the production app and one is a test app I made to test on modulus before launching. Both have identical code. Spiderable is working fine on the test app, but I'm getting the familiar

``` sh
spiderable: phantomjs failed: { [Error: Command failed: ] killed: true, code: null, signal: 'SIGTERM' } 
stderr:
```

error on the production install. Have you ever seen this??

**Comment by manybothans** [comment]
Is there anything about DNS CNAME records or single domain standard SSL certs that would cause this? Those are the only differences I can see between the two installations.

**Comment by gadicc** [comment]
hey, yeah, phantomjs has issues with some SSL certs (I think it was an SNI issue but don't recall).  see e.g. the very bottom of http://meteorpedia.com/read/spiderable

**Comment by manybothans** [comment]
thank you! :)
